// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PIMS_MS.Modules.Inventory.Database;

#nullable disable

namespace PIMS_MS.Modules.Inventory.Database.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260720235410_AddPeruvianRegions")]
    partial class AddPeruvianRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Locations", "inventory");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions", "inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Code = "AMA",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Code = "ANC",
                            Name = "Áncash"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Code = "APU",
                            Name = "Apurímac"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Code = "ARE",
                            Name = "Arequipa"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Code = "AYA",
                            Name = "Ayacucho"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Code = "CAJ",
                            Name = "Cajamarca"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Code = "CAL",
                            Name = "Callao"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Code = "CUS",
                            Name = "Cusco"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Code = "HUV",
                            Name = "Huancavelica"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            Code = "HUC",
                            Name = "Huánuco"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            Code = "ICA",
                            Name = "Ica"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            Code = "JUN",
                            Name = "Junín"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            Code = "LAL",
                            Name = "La Libertad"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            Code = "LAM",
                            Name = "Lambayeque"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000016"),
                            Code = "LIP",
                            Name = "Lima Provincias"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000017"),
                            Code = "LOR",
                            Name = "Loreto"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000018"),
                            Code = "MDD",
                            Name = "Madre de Dios"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000019"),
                            Code = "MOQ",
                            Name = "Moquegua"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000020"),
                            Code = "PAS",
                            Name = "Pasco"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000021"),
                            Code = "PIU",
                            Name = "Piura"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000022"),
                            Code = "PUN",
                            Name = "Puno"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000023"),
                            Code = "SAM",
                            Name = "San Martín"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000024"),
                            Code = "TAC",
                            Name = "Tacna"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000025"),
                            Code = "TUM",
                            Name = "Tumbes"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000026"),
                            Code = "UCA",
                            Name = "Ucayali"
                        });
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.SparePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsRework")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("SpareParts", "inventory");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SparePartId", "LocationId")
                        .IsUnique();

                    b.ToTable("Stocks", "inventory");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders", "inventory");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.WorkOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SparePartId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderItems", "inventory");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.Location", b =>
                {
                    b.HasOne("PIMS_MS.Modules.Inventory.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.Stock", b =>
                {
                    b.HasOne("PIMS_MS.Modules.Inventory.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIMS_MS.Modules.Inventory.Domain.Entities.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("PIMS_MS.Modules.Inventory.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.WorkOrderItem", b =>
                {
                    b.HasOne("PIMS_MS.Modules.Inventory.Domain.Entities.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIMS_MS.Modules.Inventory.Domain.Entities.WorkOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("PIMS_MS.Modules.Inventory.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
